Repository CarmenMariaMP/UStudy, pull requests merged in 2022-03, with the labels that each got.

#69 frontend: Vista preview curso e inscripción
  app/templates/curso.html
  app/views.py
  ustudy/urls.py
Labels: frontend, prio: medium

#70 backend: Creación de entidades
  .gitignore
  app/admin.py
  app/migrations/0003_initial.py
  app/migrations/0004_remove_notificacion_comentario_and_more.py
  app/migrations/0005_alter_notificacion_id_refencia.py
  app/migrations/0006_rename_tipo_reporte_reporte_tipo.py
  app/migrations/0007_notificacion_tipo.py
  app/migrations/0008_alter_notificacion_tipo.py
  app/models.py
  ustudy/settings.py
Labels: backend, prio: high

#76 backend: Implementacion de login y logout
  app/migrations/0009_usuario_user.py
  app/migrations/0010_alter_usuario_user.py
  app/migrations/0011_remove_usuario_user_usuario_django_user.py
  app/migrations/0012_alter_usuario_django_user.py
  app/migrations/0013_alter_usuario_django_user.py
  app/models.py
  app/templates/inicio_profesor.html
  app/templates/login.html
  app/views.py
  ustudy/urls.py
Labels: backend, prio: medium

#105 backend: Subida de archivos
  app/forms.py
  app/migrations/0014_alter_archivo_fecha_publicacion_alter_archivo_ruta.py
  app/migrations/0015_alter_archivo_ruta.py
  app/migrations/0016_alter_archivo_ruta.py
  app/models.py
  app/templates/curso.html
  app/views.py
  ustudy/settings.py
  ustudy/urls.py
Labels: backend, prio: high

#107 backend: Populate inicial de 638 asignaturas
  Initial_population/Scraping_asignaturas_json.py
  Initial_population/guia_asignaturas_populate.txt
  datos_populate_asignatura.json
Labels: backend, prio: high

#104 backend: Zona curso profesor
  app/templates/inicio_profesor.html
  app/views.py
  env.example
Labels: backend, prio: high

#106 backend: Zona alumno
  app/templates/miscursos.html
  app/views.py
Labels: backend, prio: high

#111 Feature/58 ver multimedia
  app/static/css/archivo.css
  app/templates/archivo.html
  app/views.py
  ustudy/settings.py
  ustudy/urls.py
Labels: backend, frontend, prio: medium

#118 Feature/96 subida archivos
  app/migrations/0017_alter_archivo_ruta.py
  app/models.py
  app/templates/curso.html
  app/views.py
  requirements.txt
Labels: backend, prio: high

#122 backend: Crear curso como profesor y retoque scraping
  Initial_population/Scraping_asignaturas_json.py
  app/forms.py
  app/templates/crearcurso.html
  app/views.py
  datos_populate_asignaturas.json
Labels: backend, prio: medium

#128 backend: Suscripcion a un curso
  app/templates/cursosdisponibles.html
  app/views.py
  ustudy/urls.py
Labels: backend, prio: medium

#129 Feature/126 vistas error
  app/static/css/error.css
  app/static/media/logo_roto.png
  app/templates/403_csrf.html
  app/templates/error.html
  app/views.py
  archivos/1/Tema4_Protocolos_Seguros_y_Esteganografia.pdf
  ustudy/settings.py
  ustudy/urls.py
Labels: backend, frontend, prio: medium

#131 backend: Validacion crear curso
  app/forms.py
  app/migrations/0018_alter_curso_asignatura_alter_curso_descripcion_and_more.py
  app/migrations/0019_alter_curso_asignatura_alter_curso_descripcion_and_more.py
  app/views.py
Labels: backend, prio: medium

#134 frontend: Cambio botones
  app/templates/curso.html
  app/templates/cursosdisponibles.html
  app/templates/inicio.html
  app/templates/login.html
  app/templates/miscursos.html
Labels: frontend, prio: low

#136 Feature/81 testing sprint 1
  app/tests.py
  requirements.txt
Labels: frontend, prio: low, test

#184 backend: Reporte usuario
  app/forms.py
  app/migrations/0020_reporte_archivo_reporte_usuario.py
  app/migrations/0021_alter_reporte_fecha.py
  app/migrations/0022_alter_reporte_archivo_alter_reporte_usuario.py
  app/migrations/0023_alter_archivo_fecha_publicacion_and_more.py
  app/migrations/0024_alter_archivo_fecha_publicacion_and_more.py
  app/migrations/0025_alter_archivo_fecha_publicacion.py
  app/migrations/0026_alter_archivo_fecha_publicacion.py
  app/models.py
  app/templates/archivo.html
  app/views.py
Labels: backend, prio: medium

#190 backend: Perfil usuario
  app/forms.py
  app/migrations/0020_auto_20220326_1838.py
  app/migrations/0021_alter_usuario_username.py
  app/migrations/0022_alter_usuario_username.py
  app/migrations/0023_alter_usuario_username.py
  app/migrations/0024_remove_usuario_username.py
  app/migrations/0025_alter_usuario_foto.py
  app/migrations/0026_alter_usuario_foto.py
  app/migrations/0027_merge_20220327_2032.py
  app/migrations/0028_auto_20220328_1624.py
  app/models.py
  app/templates/curso.html
  app/templates/login.html
  app/templates/perfil.html
  app/views.py
  requirements.txt
  ustudy/settings.py
  ustudy/urls.py
Labels: backend, prio: medium

#195 frontend: Perfil de usuario
  app/migrations/0029_auto_20220328_2007.py
  app/static/css/base.css
  app/static/media/avatar.png
  app/templates/base_navbar.html
  app/templates/perfil.html
  app/views.py
Labels: frontend, prio: medium
