Repository CarmenMariaMP/UStudy, pull requests merged in 2022-04, with the labels that each got.

#221 Develop
  .github/workflows/codacy.yaml
  .github/workflows/tests.yaml
  app/forms.py
  app/migrations/0031_merge_20220330_1833.py
  app/migrations/0031_merge_20220330_1846.py
  app/static/css/base.css
  app/static/css/button.css
  app/static/css/colores.css
  app/static/css/searchbar.css
  app/static/css/style.css
  app/static/css/try.css
  app/templates/archivo.html
  app/templates/base_navbar.html
  app/templates/crearcurso.html
  app/templates/curso.html
  app/templates/cursosdisponibles.html
  app/templates/inicio.html
  app/templates/inicio_profesor.html
  app/templates/login.html
  app/templates/miscursos.html
  app/templates/pasarela_pago.html
  app/templates/perfil.html
  app/templates/registro.html
  app/templates/subir_contenido.html
  app/views.py
  ustudy/settings.py
  ustudy/urls.py
Labels: frontend

#220 Feature/172 mejoras frontend s1
  .gitignore
  app/forms.py
  app/migrations/0029_auto_20220329_1133.py
  app/migrations/0030_merge_20220329_2057.py
  app/static/css/error.css
  app/templates/crearcurso.html
  app/templates/curso.html
  app/templates/cursosdisponibles.html
  app/templates/error.html
  app/templates/inicio_profesor.html
  app/templates/login.html
  app/templates/miscursos.html
  app/templates/perfil.html
  app/views.py
Labels: frontend, prio: medium

#208 backend: Dar valoración a curso
  app/static/css/valoraciones.css
  app/static/js/valoraciones.js
  app/templates/curso.html
  app/views.py
  ustudy/urls.py
Labels: backend, prio: high

#228 backend: Arreglo de miscursos
  app/views.py
Labels: backend, prio: medium

#230 backend: Obtener valoraciones
  app/templates/curso.html
  app/templates/cursosdisponibles.html
  app/templates/inicio_profesor.html
  app/templates/miscursos.html
  app/views.py
Labels: backend, prio: high

#231 Feature/188 mejoras feedback 3
  app/forms.py
  app/migrations/0030_merge_20220330_1427.py
  app/migrations/0030_merge_20220330_1915.py
  app/migrations/0031_alter_curso_suscriptores.py
  app/migrations/0033_merge_20220402_1937.py
  app/models.py
  app/templates/archivo.html
  app/templates/curso.html
  app/templates/editarcurso.html
  app/templates/inicio_profesor.html
  app/views.py
  ustudy/urls.py
Labels: backend

#240 Feature/189 actualizar perfil usuario
  app/forms.py
  app/migrations/0032_merge_20220402_1802.py
  app/migrations/0033_alter_usuario_foto.py
  app/migrations/0034_alter_usuario_foto.py
  app/models.py
  app/templates/actualizar.html
  app/templates/perfil.html
  app/views.py
  ustudy/urls.py
Labels: backend, prio: medium

#250 backend: Ajuste en views.py
  app/tests/tests_models.py
  app/views.py
Labels: backend, prio: low

#310 Feature/299 comentar contenido
  app/forms.py
  app/migrations/0002_comentario_usuario.py
  app/migrations/0003_alter_comentario_usuario.py
  app/migrations/0004_alter_comentario_responde_a.py
  app/models.py
  app/templates/actualizar.html
  app/templates/archivo.html
  app/templatetags/__init__.py
  app/templatetags/extras.py
  app/tests/tests_models.py
  app/views.py
  ustudy/urls.py
Labels: backend, prio: high

#308 backend: Suscripción modificada
  app/migrations/0008_merge_20220419_1936.py
  app/templates/curso.html
  app/templates/cursosdisponibles.html
  app/views.py
  ustudy/urls.py
Labels: backend

#318 frontend: Visualización comentarios
  app/forms.py
  app/static/css/archivo.css
  app/templates/archivo.html
Labels: frontend, prio: high

#320 fix: Suscripción
  app/templates/cursosdisponibles.html
  app/views.py
Labels: backend

#344 Fix/288 reducción malos olores
  Initial_population/Scraping_asignaturas_json.py
  app/forms.py
  app/models.py
  app/paypal.py
  app/static/css/archivo.css
  app/static/css/error.css
  app/static/css/login.css
  app/static/css/registro.css
  app/static/css/searchbar.css
  app/static/css/style.css
  app/static/css/subir_contenido.css
  app/static/css/valoraciones.css
  app/static/js/valoraciones.js
  app/tests/selenium.py
  app/tests/tests_forms.py
  app/tests/tests_models.py
  app/tests/tests_views.py
  app/views.py
Labels: prio: medium

#346 Feature/337 tests backend
  app/forms.py
  app/static/archivos/11/ISPP2122_-_SUG_-_v1.pdf
  app/templates/archivo.html
  app/templates/pasarela_pago.html
  app/tests/tests_forms.py
  app/tests/tests_models.py
  app/tests/tests_views.py
  app/views.py
Labels: backend, prio: medium
